language: python

python:
  - 3.7
  - 3.x

script:
  - pytest

deploy:
  provider: pypi
  user: marstr
  password:
    secure: PPilECobsG6iEb9Xmrlnivqg04rF1JpHiRjqhNt6RhJ3E0iWnVZmsqPf5YCxxz4cgNJEEMqz9FAbEsHx7hnTyGhyupyX5kKwS3lHa66dhfObZ/qTtBZobIXt6khWZwviRWBUwajscDBosxPi5Y6TIY103bkemR7annnDxs8bU2Zq02eChrWDcy1n8ocNUdexFC4M+6/O96ajZX9weD7uYwrVffAZXQwzlNhwlzRnhtLQ0bWwvWURil6VaBtlWfQhRRF2LpVW5v/pWXxFcuihR8IQYAMYrgFS482M95UvbAek4fqRM5MC42Axxr+GFEZRD3lL1RdKo7uX6WlHTcJ8yUe+LojTuozA0TbGUg38gf/8rIalYHg1KeTiyyYu9IC+ZAvRGjkIPMcOuICz5mJLbijnyVcVH6X6TvvjQX80kglAjH/6tdauYCoCXcElGezVjo6U1ZsRy4eQxOmTK4kFOeuvSTQXESh2xKBC06XkRv66MzUc9LLSK5PGLGTev4SCaKZeY/auHDC5X2hlgeWLdNSURQU/c27f+vIbU751P1UsYq7fr0QkLYRDzmvUc3d2uvwlfEs4rVlYc5fU91iYPKzPUeVPgHNZkMqJAvQmn1Srs0HSPYt1mgHsSs2DMzMUfFm8N6SheoGDJxh/ZWEhcc5bsADT55+oYnf4jqirOb0=
  on:
    tags: true